version: "3.9"

services:
  db-postgres: # ${POSTGRES_DOCKER_SERVICE}
    image: ${POSTGRES_DOCKER_IMAGE}
#    build:
#      context: ${POSTGRES_DOCKER_CONFIG_DOCKERFILE}
#      args:
#        DOCKER_IMAGE_FROM: ${POSTGRES_DOCKER_IMAGE_FROM}
#        INSTALL_BASH: ${ALPINE_INSTALL_BASH}
    container_name: ${POSTGRES_DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - ${POSTGRES_DB_PUBLIC_PORT}:5432
    volumes:
      - db-postgres-volume:/var/lib/postgresql/data
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${APPX_NETWORK}

volumes:
  db-postgres-volume:
