version: "3.9"

services:
  db-postgres: # ${POSTGRES_DOCKER_SERVICE}
    environment:
      # created only at the first start:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}