version: "3.9"

services:
  db-postgres: # ${POSTGRES_DOCKER_SERVICE}
    image: ${POSTGRES_DOCKER_IMAGE}
    container_name: ${POSTGRES_DOCKER_CONTAINER}
    restart: always
    ports:
      - ${POSTGRES_DB_PUBLIC_PORT}:5432
    volumes:
      - db-postgres-volume:/var/lib/postgresql/data
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}

volumes:
  db-postgres-volume:
