services:
  mn-prometheus: # ${PROMETHEUS_DOCKER_SERVICE}
    image: ${PROMETHEUS_DOCKER_IMAGE}
    container_name: ${PROMETHEUS_DOCKER_CONTAINER}
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROMETHEUS_STORAGE_TSDB_RETENTION_TIME}
      - --storage.tsdb.retention.size=${PROMETHEUS_STORAGE_TSDB_RETENTION_SIZE}
    #ports:
    #  - ${PROMETHEUS_WEB_PUBLIC_PORT}:9090
    volumes:
      - mn-prometheus-volume:/prometheus
      - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus.yml:ro
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROMETHEUS_DOCKER_SERVICE}.rule=Host(`${PROMETHEUS_WEB_DOMAIN}`)
      - traefik.http.routers.${PROMETHEUS_DOCKER_SERVICE}.entrypoints=web
      - traefik.http.routers.${PROMETHEUS_DOCKER_SERVICE}.middlewares=general-auth
      - traefik.http.services.${PROMETHEUS_DOCKER_SERVICE}.loadbalancer.server.port=9090

volumes:
  mn-prometheus-volume: