version: "3.9"

services:
  auth-keycloak: # ${KEYCLOAK_DOCKER_SERVICE}
    image: ${KEYCLOAK_DOCKER_IMAGE}
    container_name: ${KEYCLOAK_DOCKER_CONTAINER}
    restart: always
    command: start-dev
    ports:
      - ${KEYCLOAK_WEB_PUBLIC_PORT}:8080
    environment:
      - TZ=${APPX_TZ}
      - KEYCLOAK_ADMIN=${KEYCLOAK_WEB_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_WEB_ADMIN_PASSWORD}
    networks:
      - local-network