version: "3.9"

services:
  db-redis: # ${REDIS_DOCKER_SERVICE}
    image: ${REDIS_DOCKER_IMAGE}
    container_name: ${REDIS_DOCKER_CONTAINER}
    privileged: true
    restart: always
    ports:
      - ${REDIS_PUBLIC_PORT}:6379
    volumes:
      - db-redis-volume:/data
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}

volumes:
  db-redis-volume:
    driver: local