version: "3.9"

services:
  db-mongo: # ${MONGO_DOCKER_SERVICE}
    image: ${MONGO_DOCKER_IMAGE}
    container_name: ${MONGO_DOCKER_CONTAINER}
    restart: always
    ports:
      - ${MONGO_DB_PUBLIC_PORT}:27017
    volumes:
      - db-mongo-volume:/data/db
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network

volumes:
  db-mongo-volume:
