services:
  web-app: # ${PHP_FPM_DOCKER_SERVICE}
    image: ${PHP_FPM_DOCKER_IMAGE}
    container_name: ${PHP_FPM_DOCKER_CONTAINER}
    restart: unless-stopped
    #ports:
    #  - "127.0.0.1:9000:9000"
    #  - "127.0.0.1:9003:9003"
    volumes:
      - ${APPX_WORK_DIR}:/opt/app
    environment:
      - TZ=${APPX_TZ}
      - APPX_VER=${APPX_VER}
    env_file:
      - ${PHP_FPM_APPX_ENV_FILE}
    networks:
      - local-network
    labels:
      - traefik.enable=false

  web-app-nginx: # ${PHP_FPM_NGINX_DOCKER_SERVICE}
    image: ${PHP_FPM_NGINX_DOCKER_IMAGE}
    container_name: ${PHP_FPM_NGINX_DOCKER_CONTAINER}
    restart: unless-stopped
    depends_on:
      - web-app
    #ports:
    # - ${PHP_FPM_WEBAPP_PUBLIC_PORT}:80
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PHP_FPM_NGINX_DOCKER_SERVICE}.rule=Host(`${PHP_FPM_WEBAPP_DOMAIN}`)
      - traefik.http.routers.${PHP_FPM_NGINX_DOCKER_SERVICE}.entrypoints=web
      - traefik.http.services.${PHP_FPM_NGINX_DOCKER_SERVICE}.loadbalancer.server.port=80