version: "3.9"

services:
  web-app: # ${PHP_FPM_DOCKER_SERVICE}
    image: ${PHP_FPM_DOCKER_IMAGE}
    container_name: ${PHP_FPM_DOCKER_CONTAINER}
    restart: always
    # ports:
    #  - "127.0.0.1:9000:9000"
    #  - "127.0.0.1:9003:9003"
    volumes:
      - ${APPX_WORK_DIR}:/opt/app
    environment:
      - TZ=${APPX_TZ}
#      - APPX_DB_HOST=${PHP_FPM_DB_HOST}
#      - APPX_DB_PORT=${PHP_FPM_DB_PORT}
#      - APPX_DB_NAME=${PHP_FPM_DB_NAME}
#      - APPX_DB_USER=${PHP_FPM_DB_USER}
#      - APPX_DB_PASSWORD=${PHP_FPM_DB_PASSWORD}
#      - APPX_REDIS_HOST=${PHP_FPM_REDIS_HOST}
#      - APPX_REDIS_PORT=${PHP_FPM_REDIS_PORT}
#      - APPX_REDIS_PASSWORD=${PHP_FPM_REDIS_PASSWORD}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}

  web-app-nginx: # ${PHP_FPM_NGINX_DOCKER_SERVICE}
    image: ${PHP_FPM_NGINX_DOCKER_IMAGE}
    container_name: ${PHP_FPM_NGINX_DOCKER_CONTAINER}
    restart: always
    depends_on:
      - web-app
    ports:
      - ${PHP_FPM_WEBAPP_PUBLIC_PORT}:80
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${READONLY_PHP_FPM_DOCKER_HOST}.rule=Host(`${PHP_FPM_WEBAPP_DOMAIN}`)
      - traefik.http.routers.${READONLY_PHP_FPM_DOCKER_HOST}.entrypoints=web
      - traefik.http.services.${READONLY_PHP_FPM_DOCKER_HOST}.loadbalancer.server.port=80