version: "3.9"

services:
  mn-nodeexporter: # ${NODEEXPORTER_DOCKER_SERVICE}
    image: ${NODEEXPORTER_DOCKER_IMAGE}
    container_name: ${NODEEXPORTER_DOCKER_CONTAINER}
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network