version: "3.9"

services:
  web-app: # ${GO_DOCKER_SERVICE}
    image: ${GO_DOCKER_IMAGE}
    container_name: ${GO_DOCKER_CONTAINER}
    restart: always
    command:
      - go
      - run
      - ${GO_APP_MAIN_FILE}
    ports:
      - ${GO_WEBAPP_PUBLIC_PORT}:${GO_WEBAPP_PORT}
    volumes:
      - ${GO_GOPATH_DIR}:/go
      - ${APPX_WORK_DIR}:/opt/app
    environment:
      - TZ=${APPX_TZ}
      - APPX_SERVICE_BIND=${GO_WEBAPP_BIND}
      - APPX_SERVICE_PORT=${GO_WEBAPP_PORT}
    networks:
      - local-network