version: "3.9"

services:
  web-app: # ${GO_DOCKER_SERVICE}
    image: ${GO_DOCKER_IMAGE}
    container_name: ${GO_DOCKER_CONTAINER}
    restart: unless-stopped
    command:
      - go
      - run
      - ${GO_APPX_MAIN_FILE}
    ports:
      - ${GO_WEBAPP_PUBLIC_PORT}:${GO_WEBAPP_INTERNAL_PORT}
    volumes:
      - ${GO_GOPATH_DIR}:/go
      - ${APPX_WORK_DIR}:/opt/app
    environment:
      - TZ=${APPX_TZ}
      - APPX_VER=${APPX_VER}
    env_file:
      - ${GO_APPX_ENV_FILE}
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${GO_DOCKER_SERVICE}.rule=Host(`${GO_WEBAPP_DOMAIN}`)
      - traefik.http.routers.${GO_DOCKER_SERVICE}.entrypoints=web
      - traefik.http.services.${GO_DOCKER_SERVICE}.loadbalancer.server.port=${GO_WEBAPP_INTERNAL_PORT}