version: "3.9"

services:
  proxy-nginx:
    build:
      context: ${NGINX_DOCKER_CONFIG_DIR}
      args:
        DOCKER_IMAGE: ${NGINX_DOCKER_IMAGE}
        INSTALL_BASH: ${NGINX_INSTALL_BASH}
        SERVICE_TYPE: ${NGINX_SERVICE_TYPE}
        SERVICE_DOMAIN: ${NGINX_SERVICE_DOMAIN}
        SERVICE_HOST: ${NGINX_SERVICE_HOST}
        SERVICE_PORT: ${NGINX_SERVICE_PORT}
    container_name: ${NGINX_DOCKER_CONTAINER}
    restart: unless-stopped
    depends_on:
      - web-app
    ports:
      - "${NGINX_EXT_PORT}:80"
    environment:
      - TZ=${NGINX_TZ}
    networks:
      - ${NGINX_DOCKER_NETWORK}