version: "3.9"

services:
  broker-kafka-ui: # ${KAFKA_UI_DOCKER_SERVICE}
    image: ${KAFKA_UI_DOCKER_IMAGE}
    container_name: ${KAFKA_UI_DOCKER_CONTAINER}
    restart: unless-stopped
    #ports:
    #  - ${KAFKA_UI_WEB_PUBLIC_PORT}:${KAFKA_UI_WEB_INTERNAL_PORT}
    environment:
      - TZ=${APPX_TZ}
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_UI_KAFKA_HOSTS_PORTS}
      - KAFKA_CLUSTERS_0_ZOOKEEPER=${KAFKA_UI_ZOOKEEPER_HOST_PORT}
      - KAFKA_CLUSTERS_0_READONLY=false
      - SERVER_PORT=${KAFKA_UI_WEB_INTERNAL_PORT}
      - DYNAMIC_CONFIG_ENABLED=false
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${KAFKA_UI_DOCKER_SERVICE}.rule=Host(`${KAFKA_UI_WEB_DOMAIN}`)
      - traefik.http.routers.${KAFKA_UI_DOCKER_SERVICE}.entrypoints=web
      - traefik.http.routers.${KAFKA_UI_DOCKER_SERVICE}.middlewares=general-auth
      - traefik.http.services.${KAFKA_UI_DOCKER_SERVICE}.loadbalancer.server.port=${KAFKA_UI_WEB_INTERNAL_PORT}