version: "3.9"

services:
  broker-kafka-ui: # ${KAFKA_UI_DOCKER_SERVICE}
    image: ${KAFKA_UI_DOCKER_IMAGE}
    container_name: ${KAFKA_UI_DOCKER_CONTAINER}
    restart: always
    environment:
      - TZ=${APPX_TZ}
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_UI_KAFKA_HOSTS_PORTS}
      - KAFKA_CLUSTERS_0_ZOOKEEPER=${KAFKA_UI_ZOOKEEPER_HOST_PORT}
      - KAFKA_CLUSTERS_0_READONLY=false
      - SERVER_PORT=${KAFKA_UI_WEB_INTERNAL_PORT}
      - DYNAMIC_CONFIG_ENABLED=false
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${READONLY_KAFKA_UI_DOCKER_HOST}.rule=Host(`${KAFKA_UI_WEB_DOMAIN}`)
      - traefik.http.routers.${READONLY_KAFKA_UI_DOCKER_HOST}.entrypoints=web
      - traefik.http.services.${READONLY_KAFKA_UI_DOCKER_HOST}.loadbalancer.server.port=${KAFKA_UI_WEB_INTERNAL_PORT}