services:
  db-cassandra: # ${CASSANDRA_DOCKER_SERVICE}
    image: ${CASSANDRA_DOCKER_IMAGE}
    container_name: ${CASSANDRA_DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - ${CASSANDRA_DB_PUBLIC_PORT}:9042
    volumes:
      - db-cassandra-volume:/var/lib/cassandra
    environment:
      - TZ=${APPX_TZ}
#      - CASSANDRA_LISTEN_ADDRESS=${CASSANDRA_LISTEN_ADDRESS}
#      - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
#      - CASSANDRA_RPC_ADDRESS=${CASSANDRA_RPC_ADDRESS}
#      - CASSANDRA_START_RPC=${CASSANDRA_START_RPC}
#      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
#      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
#      - CASSANDRA_NUM_TOKENS=${CASSANDRA_NUM_TOKENS}
#      - CASSANDRA_DC=${CASSANDRA_DC}
#      - CASSANDRA_RACK=${CASSANDRA_RACK}
#      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
    networks:
      - local-network
    labels:
      - traefik.enable=false

volumes:
  db-cassandra-volume: