version: "3.9"

services:
  db-mysql: # ${MYSQL_DOCKER_SERVICE}
    image: ${MYSQL_DOCKER_IMAGE}
#    build:
#      context: ${MYSQL_DOCKER_CONFIG_DOCKERFILE}
#      args:
#        DOCKER_IMAGE_FROM: ${MYSQL_DOCKER_IMAGE_FROM}
    platform: linux/x86_64
    container_name: ${MYSQL_DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - ${MYSQL_DB_PUBLIC_PORT}:3306
    volumes:
      - db-mysql-volume:/var/lib/mysql
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${APPX_NETWORK}

volumes:
  db-mysql-volume: