version: "3.9"

services:
  db-mysql: # ${MYSQL_DOCKER_SERVICE}
    image: ${MYSQL_DOCKER_IMAGE}
    platform: linux/x86_64
    container_name: ${MYSQL_DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - ${MYSQL_DB_PUBLIC_PORT}:3306
    volumes:
      - db-mysql-volume:/var/lib/mysql
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network
    labels:
      - traefik.enable=false

volumes:
  db-mysql-volume: