version: "3.9"

services:
  db-mysql: # ${MYSQL_DOCKER_SERVICE}
    image: ${MYSQL_DOCKER_IMAGE}
    platform: linux/x86_64
    container_name: ${MYSQL_DOCKER_CONTAINER}
    restart: always
    ports:
      - ${MYSQL_DB_PUBLIC_PORT}:3306
    volumes:
      - db-mysql-volume:/var/lib/mysql
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}

volumes:
  db-mysql-volume: