ARG DOCKER_IMAGE_FROM=cassandra:4.1.3

FROM ${DOCKER_IMAGE_FROM}

#COPY cassandra.yaml /opt/cassandra/conf/cassandra.yaml

#CMD ["cassandra", "--config", "/etc/cassandra/cassandra.conf"]

#EXPOSE 9042
