version: "3.9"

services:
  s3-minio: # ${MINIO_DOCKER_SERVICE}
    image: ${MINIO_DOCKER_IMAGE}
    container_name: ${MINIO_DOCKER_CONTAINER}
    command:
      - server
      - /data
      - --console-address
      - ":${MINIO_WEB_INTERNAL_PORT}"
    restart: unless-stopped
    ports:
      - ${MINIO_API_PUBLIC_PORT}:${MINIO_API_INTERNAL_PORT}
    volumes:
      - s3-minio-volume:/data
    environment:
      - TZ=${APPX_TZ}
      - MINIO_ROOT_USER=${MINIO_API_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_API_PASSWORD}
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 30s
      retries: 3

  s3-minio-nginx: # ${MINIO_NGINX_DOCKER_SERVICE}
    image: ${MINIO_NGINX_DOCKER_IMAGE}
    container_name: ${MINIO_NGINX_DOCKER_CONTAINER}
    restart: unless-stopped
    depends_on:
      - s3-minio
    #ports:
    #  - ${MINIO_NGINX_PUBLIC_PORT}:80
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${MINIO_NGINX_DOCKER_SERVICE}.rule=Host(`${MINIO_WEB_DOMAIN}`)
      - traefik.http.routers.${MINIO_NGINX_DOCKER_SERVICE}.entrypoints=web
      - traefik.http.services.${MINIO_NGINX_DOCKER_SERVICE}.loadbalancer.server.port=80

volumes:
  s3-minio-volume: