version: "3.9"

services:
  s3-minio: # ${MINIO_DOCKER_SERVICE}
    image: ${MINIO_DOCKER_IMAGE}
    container_name: ${MINIO_DOCKER_CONTAINER}
    command:
      - server
      - /data
      - --console-address
      - ":${MINIO_WEB_PORT}"
    restart: always
    ports:
      - ${MINIO_API_PUBLIC_PORT}:9000
    #  - 127.0.0.1:${MINIO_WEB_PORT}:${MINIO_WEB_PORT}
    volumes:
      - s3-minio-volume:/data
    environment:
      - TZ=${APPX_TZ}
      - MINIO_ROOT_USER=${MINIO_API_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_API_PASSWORD}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 30s
      retries: 3

  s3-minio-nginx: # ${MINIO_NGINX_DOCKER_SERVICE}
    image: ${MINIO_NGINX_DOCKER_IMAGE}
    container_name: ${MINIO_NGINX_DOCKER_CONTAINER}
    restart: always
    depends_on:
      - s3-minio
    ports:
      - ${MINIO_WEB_PUBLIC_PORT}:80
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}

volumes:
  s3-minio-volume: