version: "3.9"

services:
  db-mysql:
    build:
      context: ${MYSQL_DOCKER_CONFIG_DIR}
      args:
        DOCKER_IMAGE: ${MYSQL_DOCKER_IMAGE}
    platform: linux/x86_64
    container_name: ${MYSQL_DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - "${MYSQL_EXT_PORT}:3306"
    volumes:
      - db-mysql-volume:/var/lib/mysql
    environment:
      - TZ=${MYSQL_TZ}
      - MYSQL_DB_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD} # only the first time
      - MYSQL_DATABASE=${MYSQL_DB_NAME} # only the first time
      - MYSQL_USER=${MYSQL_DB_USER} # only the first time
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD} # only the first time
    networks:
      - ${MYSQL_DOCKER_NETWORK}

volumes:
  db-mysql-volume: