version: "3.9"
services:

  s3-minio:
    build:
      context: ${MINIO_DOCKER_CONFIG_DIR}
      args:
        DOCKER_IMAGE: ${MINIO_DOCKER_IMAGE}
    container_name: ${MINIO_DOCKER_CONTAINER}
    command: server /data --console-address ":${MINIO_WEB_PORT}"
    restart: unless-stopped
    #ports:
    #  - "127.0.0.1:9000:9000"
    #  - "127.0.0.1:9001:${MINIO_WEB_PORT}"
    volumes:
      - s3-minio-volume:/data
    environment:
      - TZ=${MINIO_TZ}
      - MINIO_ROOT_USER=${MINIO_WEB_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_WEB_ROOT_PASSWORD}
    networks:
      - ${MINIO_DOCKER_NETWORK}

  s3-minio-nginx:
    build:
      context: ${NGINX_DOCKER_CONFIG_DIR}
      args:
          DOCKER_IMAGE: ${NGINX_DOCKER_IMAGE}
          INSTALL_BASH: ${NGINX_INSTALL_BASH}
          SERVICE_TYPE: appx
          SERVICE_DOMAIN: ${MINIO_WEB_DOMAIN}
          SERVICE_HOST: s3-minio
          SERVICE_PORT: ${MINIO_WEB_PORT}
    container_name: ${NGINX_DOCKER_CONTAINER}
    restart: unless-stopped
    depends_on:
      - s3-minio
    ports:
      - "${MINIO_WEB_EXT_PORT}:80"
    environment:
      - TZ=${NGINX_TZ}
    networks:
      - ${MINIO_DOCKER_NETWORK}

volumes:
  s3-minio-volume: