version: "3.9"

services:
  db-postgres:
    build:
      context: ${POSTGRES_DOCKER_CONFIG_DIR}
      args:
        DOCKER_IMAGE: ${POSTGRES_DOCKER_IMAGE}
        INSTALL_BASH: ${POSTGRES_INSTALL_BASH}
    platform: linux/x86_64
    container_name: ${POSTGRES_DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - "${POSTGRES_DB_EXT_PORT}:5432"
    volumes:
      - db-postgres-volume:/var/lib/postgresql/data
    environment:
      - TZ=${POSTGRES_TZ}
      - POSTGRES_DB=${POSTGRES_DB_NAME} # only the first time
      - POSTGRES_USER=${POSTGRES_DB_USER} # only the first time
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD} # only the first time
      # - PGDATA=/pgdata
    networks:
      - ${POSTGRES_DOCKER_NETWORK}

volumes:
  db-postgres-volume:
