version: "3.9"

services:
  web-app: # ${NODEJS_DOCKER_SERVICE}
    image: ${NODEJS_DOCKER_IMAGE}
    container_name: ${NODEJS_DOCKER_CONTAINER}
    restart: always
    command:
      - npm
      - run
      - start
    ports:
      - ${NODEJS_WEBAPP_PUBLIC_PORT}:${NODEJS_WEBAPP_PORT}
    volumes:
      - ${APPX_WORK_DIR}:/opt/app
    environment:
      - TZ=${APPX_TZ}
    networks:
      - ${DOCKER_COMPOSE_LOCAL_NETWORK}