version: "3.9"

services:
  web-app: # ${NODEJS_DOCKER_SERVICE}
    image: ${NODEJS_DOCKER_IMAGE}
    container_name: ${NODEJS_DOCKER_CONTAINER}
    restart: unless-stopped
    command:
      - npm
      - run
      - start
    ports:
      - ${NODEJS_WEBAPP_PUBLIC_PORT}:3000
    volumes:
      - ${APPX_WORK_DIR}:/opt/app
    environment:
      - TZ=${APPX_TZ}
      - APPX_VER=${APPX_VER}
    env_file:
      - ${NODEJS_APPX_ENV_FILE}
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NODEJS_DOCKER_SERVICE}.rule=Host(`${NODEJS_WEBAPP_DOMAIN}`)
      - traefik.http.routers.${NODEJS_DOCKER_SERVICE}.entrypoints=web
      - traefik.http.services.${NODEJS_DOCKER_SERVICE}.loadbalancer.server.port=3000