services:
  proxy-traefik: # ${TRAEFIK_DOCKER_SERVICE}
    image: ${TRAEFIK_DOCKER_IMAGE}
    container_name: ${TRAEFIK_DOCKER_CONTAINER}
    restart: unless-stopped
    command:
      # - --log.level=DEBUG
      # api
      - --api.dashboard=true
      - --api.insecure=true
      # providers
      - --providers.docker
      - --providers.docker.network=${TRAEFIK_DOCKER_NETWORK}
      - --providers.docker.exposedByDefault=false
      # entryPoints
      # * web, db
      - --entryPoints.web.address=:80
      - --entryPoints.postgres.address=:5432
      - --entryPoints.redis.address=:6379
      # change api port
      - --entryPoints.traefik.address=:${TRAEFIK_API_INTERNAL_PORT}
    ports:
      - ${TRAEFIK_PROXY_PUBLIC_PORT}:80
    #  - 127.0.0.1:443:443
      - 127.0.0.1:5432:5432
      - 127.0.0.1:6379:6379
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${APPX_TZ}
    networks:
      - local-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-api.rule=Host(`${TRAEFIK_WEB_DOMAIN}`)
      - traefik.http.routers.traefik-api.entrypoints=web
      - traefik.http.routers.traefik-api.service=api@internal
      - traefik.http.routers.traefik-api.middlewares=general-auth
      - traefik.http.services.traefik-api.loadbalancer.server.port=${TRAEFIK_API_INTERNAL_PORT}
      # Basic Auth:
      # `apt install apache2-utils` or `apk add apache2-utils`
      # echo $(htpasswd -nBC 10 "{userName}") | sed -e s/\\$/\\$\\$/g
      - traefik.http.middlewares.general-auth.basicauth.users=admin:$$2y$$10$$0xREzqdZjOHaiRqZzkTL3.PbwfnsDAF3dwqcsA6JDbVF7MGSbONJm